### ISSUE TITLE
new idea (1)

### ISSUE THREAD

**Issue by Alucardaria** [calexil/Tatakai#3]
you should add a character who has a wide variety of weapons that are incorperated into each button example(high being gun shot, standard is a sword, low is a scythe) and make it where they have a blood lusted move where all weapoms are upgraded and doo extra damage, but suffer a drawback after this time period is over.

**Comment by calexil** [comment]
super complicated, may add something like this later(unlockable)

**Comment by Alucardaria** [comment]
or how about a character who uses there shadow to fight and uses a pocket knife. i could imagine this character being crazy and sadistic but there is a cold truth to when they talk to a character. they could use the shadow called limbo(name is up to you really) to continue attacks along with the knife. this character could be a glass cannon type
